language: python

notifications:
  email: false

python:
  - "3.6"

matrix:
  include:
    - env: TEST=standard
      os: linux
    - env: TEST=flake
      os: linux
  allow_failures:
    - env: TEST=flake
install:
  # - sudo apt-get update
  # Deactivate travis environnement :
  - deactivate
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION numpy scipy joblib matplotlib
  - source activate testenv
  - pip install setuptools mne pandas statsmodels
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install flake8 pep8-naming;
  - pip install .

script:
    - if [[ "${TEST}" == "standard" ]]; then
          py.test --cov;
      elif [[ "${TEST}" == "flake" ]]; then
          flake8;
      fi;

after_success:
  - codecov
